### ISSUE TITLE
mvn to bundle self-contained zip with everything ready to run?

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-xebium-bridge#3]
Hi @fhoeben ,

In hsac-fixtures you have this:

```
mvn clean compile dependency:copy-dependencies assembly:single
```

Which is great because I can unzip the file it produces and I have everything I need to run. Plug and Play.

So... I was telling a friend about your fixture and he also needs this xebium bridge. I told him to run the same thing here in this project:

```
mvn clean compile dependency:copy-dependencies assembly:single
```

However, this zips just JARs. :-(

Is it possible to facilitate things here like you did with hsac-fixtures? Or are users expected to produce their own POM file and point at everything? (this is what I did for myself, btw - my own pom file).

Thanks!

**Comment by fhoeben** [comment]
The idea for that zip is that you combine both zips:
- Take the zip in hsac-fixtures and unzip that somewhere (let's say $WIKI)
- Take the zip in the xebium-bridge and unzip that so that the jars end up in the (already created in the previous step) `fixtures` directory below $WIKI

Then the standalone installation also supports the xebium-bridge
